# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'proto.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bproto.proto\x12\x08\x65lection\"!\n\x0f\x45lectionRequest\x12\x0e\n\x06region\x18\x01 \x01(\t\"4\n\x10\x45lectionResponse\x12\x11\n\tcandidate\x18\x01 \x01(\t\x12\r\n\x05votes\x18\x02 \x01(\x05\x32[\n\x0c\x45lectionData\x12K\n\x12GetElectionResults\x12\x19.election.ElectionRequest\x1a\x1a.election.ElectionResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ELECTIONREQUEST']._serialized_start=25
  _globals['_ELECTIONREQUEST']._serialized_end=58
  _globals['_ELECTIONRESPONSE']._serialized_start=60
  _globals['_ELECTIONRESPONSE']._serialized_end=112
  _globals['_ELECTIONDATA']._serialized_start=114
  _globals['_ELECTIONDATA']._serialized_end=205
# @@protoc_insertion_point(module_scope)
